### ISSUE TITLE
Keyboard shortcut ?

### ISSUE THREAD

**Issue by thierry-laval** [streetsidesoftware/vscode-cspell-dict-extensions#63]
Do you have a keyboard shortcut to select several words to add to the dictionary?

**Comment by Jason3S** [comment]
There are a few ways.

## Using the Context Menu
1. Select the text that contains the words.
    
    ![image](https://user-images.githubusercontent.com/3740137/133686883-2bf5ffc8-266a-469a-83dc-c604b61a48d9.png)

2. Right click to bring up the context menu.
3. Select add all spelling issues to dictionary.
   ![image](https://user-images.githubusercontent.com/3740137/133687130-0213fa86-edf8-4bd9-b600-ad90780ac51e.png)

It will add the underlined words to your dictionary.

If you choose add word instead of all all word, it will give you a choice on which words to add.

**Comment by thierry-laval** [comment]
Thank a lot :-)
